name = "Sequent"
uuid = "3406161f-1d61-4e4e-ab9c-e99e0c076c20"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
MLStyle = "0.4"
julia = "1"

[extras]
HMRowUnification = "1f764b34-43ae-408e-9bb4-377386bc1704"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HMRowUnification"]
